site_name: Mon site web

language: fr

nav:
  - Home: index.md
  - Test: test.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: deep purple
    accent: indigo


  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: black
    accent: white
